spring:
  application:
    name: serviceflow

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:serviceflow}
    username: ${DB_USERNAME:serviceflow}
    password: ${DB_PASSWORD:}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
          include: health,info

  endpoint:
    health:
      show-details: NEVER